### ISSUE TITLE
Validating an SLD XML string

### ISSUE THREAD

**Issue by rowanwins** [geostyler/geostyler-sld-parser#276]
# Feature Request

**Is your feature request related to a problem? Please describe.**
I've been looking for a js library to validate a SLD XML string.

**Describe the solution you'd like**
I'd like to a method which takes an xml string and returns a boolean as to whether it's valid or not.
````
const isValid = geostylerSldParser.isSldValid(xmlString)
````

**Describe alternatives you've considered**
Doesn't look like there are any other js libs out there working on SLD stuff :(

**Additional context**

Thanks for sharing what looks like an interesting library!

**Comment by jansule** [comment]
> Doesn't look like there are any other js libs out there working on SLD stuff

I think [jsonix](http://www.jsonix.org/)  might be what you are looking for. It's a json-xml parser

> Jsonix advantages:
>
> - Strongly structured.
> - Type-safe.
> - (Optionally) XML Schema-driven.

As you can see, it supports xml schema and the same maintainer also provides some schemas for ogc standards https://github.com/highsource/ogc-schemas

Besides that, I'm not sure if this is a task for geostyler-sld-parser, or rather a dedicated xml validator, as it would work well standalone.

Also this would break the consistent API with our other parsers, which I would like to keep as clean and simple as possible.

@KaiVolland what do you think?

---
> Thanks for sharing what looks like an interesting library!

Happy to hear that there is an interest in our library.

**Comment by rowanwins** [comment]
Wow - great find @jansule , that could indeed fill the need. And yeah if there is something already out there that fits the bill then it makes sense to use it rather then pollute this library.
