### ISSUE TITLE
SLD 1.1.0 vs SLD 1.0.0

### ISSUE THREAD

**Issue by jansule** [geostyler/geostyler-sld-parser#288]
# Feature Request

**Is your feature request related to a problem? Please describe.**

Currently we always write SLD 1.0.0, even though a SLD 1.1.0 was initially given. We also downgrade some 1.1.0 features e.g. `SvgParameter` vs `CssParameter`.

**Describe the solution you'd like**

We should clearly distinguish between the different SLD versions and be able to read/write both properly.

We should either create two completely distinct parsers for each version, respectively, or add a switch to distinguish between the different versions.

**Comment by KaiVolland** [comment]
We could create subfolders in the src folder. One for 1.0.0 and one for 1.1.0.
Maybe @hwbllmnn @mrsnyder have some thoughts too.

**Comment by weskamm** [comment]
In terms of readability, a separate class / folder structure would be nice. But looking at it in detail, i would try to handle the changes in the exisiting class. This would save lots of duplicated code and should be too much of new code added.

As far as i can see the main troubles are in the SLD write method. 
I suggest having a config prop that indicates if symbology encoding, and thus SLD 1.1.0 and the `se` namespace should be used.

Main thing to fixup is writing out the different Syntax (order, se-prefix, CSSParameter -> SvgParameter)
As i already started, please give feedback if there is something to discuss

**Comment by hwbllmnn** [comment]
Somehow missed this, sorry. I agree with @weskamm , SLD/SE 1.0.0/1.1.0 are really mainly congruent, separating the writers  would mean duplicating a lot of code. I also agree with the notion of having a config prop for this, so we can read SLD 1.0.0 and write it out as SLD/SE 1.1.0.

**Comment by dnlkoch** [comment]
For shared code I would introduce an abstract class the different version parsers could extend from. IMHO having multiple type conditions across a huge class _might_ complicate readability and maintainability.

**Comment by weskamm** [comment]
Changes are smaller than you feared:

https://github.com/geostyler/geostyler-sld-parser/pull/289/files#diff-03b9f5ee99035e0bf89d2385871c79bce270f81666e5bf0cc8e4a13ccbfe3f15

**Comment by KaiVolland** [comment]
Is the symbology encoding the only difference between 1.0.0 and 1.1.0?

**Comment by weskamm** [comment]
http://opengeospatial.github.io/e-learning/se/text/main.html

**Comment by KaiVolland** [comment]
Solved with https://github.com/geostyler/geostyler-sld-parser/pull/289
