### ISSUE TITLE
更新版本后数据问题

### ISSUE THREAD

**Issue by admins123C** [geostyler/geostyler-sld-parser#505]
# Question

你们版本更新为什么获取的数据会被添加output 从2.4.0到3.0.1版本更新后出现的问题 数据格式改了嘛？

**Comment by marcjansen** [comment]
An online translator gives the following translation:


**Data problems after updating the version**

Why is the data obtained by your version update added to the output? The problem occurred after the update from version 2.4.0 to 3.0.1. Has the data format changed?

(Not an optimal translation but maybe we can say something in this regard)

**Comment by marcjansen** [comment]
@admins123C Maybe this migration information here helps, as the output indeed has changed (hence the SemVer major release): https://github.com/geostyler/geostyler-sld-parser/releases/tag/v3.0.0
