### ISSUE TITLE
doesnt work with vite

### ISSUE THREAD

**Issue by yang6626** [geostyler/geostyler-sld-parser#560]
# Bug

**Describe the bug**
vue3 + vite
import SLDParser from "geostyler-sld-parser";
const parser = new SLDParser();
return error when call parser.readStyle

but when i use <script src="/node_modules/geostyler-sld-parser/browser/sldStyleParser.js"></script> work fine;

**Screenshots**
![image](https://user-images.githubusercontent.com/63634780/162552746-18af65f2-1911-460a-8bb3-27fdc0fd325a.png)

**Additional context**

**Comment by jansule** [comment]
Thanks for the info @yang6626 

Which version of the geostyler-sld-parser are you using?

I am not familiar with vite, but there might be some build configuration missing.

**Comment by yang6626** [comment]
thanks for the reply @jansule  
i'm using 3.2.2

**Comment by yang6626** [comment]
this package use xml2js which use node environment "events"，use command "npm install events" to fix the error.
