### ISSUE TITLE
Test Suite Fails on Windows due to Line Endings

### ISSUE THREAD

**Issue by geographika** [geostyler/geostyler-sld-parser#625]
# Bug

**Describe the bug**

4 tests fail due to line ending differences:

+ SldStyleParser implements StyleParser › #writeStyle › creates the correct order in a text symbolizer `'./data/slds/1.0/unsupported_properties.sld' `
+ SldStyleParser implements StyleParser › #writeStyle › creates the correct order in a text symbolizer `'./data/slds/1.1/unsupported_properties.sld' `
+ SldStyleParser with Symbology Encoding implements StyleParser › #writeStyle › adds unsupportedProperties to the write output `'./data/slds/1.0/point_styledLabel_elementOrder.sld'`
+ SldStyleParser with Symbology Encoding implements StyleParser › #writeStyle › adds unsupportedProperties to the write output `'./data/slds/1.1/point_styledLabel_elementOrder.sld'`

All the above test cases 

```
      880 |       expect(warnings).toEqual(warningsGot);
      881 |       const sld = fs.readFileSync('./data/slds/1.0/unsupported_properties.sld', 'utf8');
    > 882 |       expect(sldString).toEqual(sld.trim());
```

It is caused by the following function:

https://github.com/geostyler/geostyler-sld-parser/blob/44fc5fad0dd90fb1f116bac52a6d7f4c5e295278/src/SldStyleParser.ts#L1027

This writes out to the SLD using LF rather than CRLF, which then makes the comparison fail.
Are the line endings added by `.join('');`?

Note my git settings checkout files using `CRLF` so all other files are passing. One "fix" is to change the failing test cases to use `LF`. 
Another hacky fix is to get rid of all whitespace in the comparisons (but that makes

```
Tests:       4 failed, 182 passed, 186 total
```

**To Reproduce**

On a Windows machine:

``npm test``

**Comment by hwbllmnn** [comment]
I'd strongly suggest to use `core.eol = lf` in your gitconfig, all tools/editors I know will work perfectly with this on windows. That way the tests probably won't fail.

**Comment by geographika** [comment]
Thanks @hwbllmnn - always checking out with LF results in the full test suite passing. 
I can close this - but does anyone have an idea why only the 4 tests fails - all the other tests passed on Windows with CRLF in the data SLD files. Is there something different when writing files in the 4 test cases?

**Comment by geographika** [comment]
Ah ok that makes sense - thanks. I think the failing tests need to populate a template and write the file.
