### ISSUE TITLE
Internet Explorer 11 Support

### ISSUE THREAD

**Issue by geographika** [geostyler/geostyler-sld-parser#677]
# Question

Has Internet Explorer 11 support been "officially" dropped for geostyle-sld-parser?

The `package.json` currently contains the following:

https://github.com/geostyler/geostyler-sld-parser/blob/4c4c47b3fef35a425cf844f336a83eb53d96137c/package.json#L78

The npm builds include syntax that throws errors in IE11 e.g. `2 ** 24` which would need to be replaced with `Math.pow(2, 24)` (as per https://stackoverflow.com/a/33284586/179520). I presume there could be some way of building IE11 compatible versions using babel. 

No problems if support has been dropped - we're just assessing how feasible it is to continue IE11 support.

**Comment by jansule** [comment]
Yes, support for Internet Explorer has been dropped. Actually, it was never really intended to be supported in the first place (at least with regard to any UI related things).

We should definitely remove this info from the package.json.

**Comment by geographika** [comment]
Thanks @jansule. Should package.json simply have that line removed?

**Comment by jansule** [comment]
It might be better to only remove the `< 9` part so it will say `"not ie"`. This makes clear that we do not support IE
