### ISSUE TITLE
Extract SLD version from SLD

### ISSUE THREAD

**Issue by KaiVolland** [geostyler/geostyler-sld-parser#696]
# Feature Request

It would be a nice feature to read the SLD version when reading an SLD automatically.

@rdewit mentioned here: https://github.com/geostyler/geostyler-sld-parser/pull/682#issuecomment-1250429210

> The reason that I'm asking is because when we use the SLD parser in our code, we now 'manually' extract it with using the following (also using fast-xml-parser) just to get that version information:
[...]
We then feed that version value as option in the constructor of the SLD parser. It seems that automatically extracting it from the SLD would be a logical next step.

**Comment by jansule** [comment]
Added in https://github.com/geostyler/geostyler-sld-parser/pull/926
