### ISSUE TITLE
If textSymbolizer opacity equal to 0, xml change to 1

### ISSUE THREAD

**Issue by liqpy** [geostyler/geostyler-sld-parser#912]
# Bug
**surce code**
[CssParameter]: [{
    '#text': textSymbolizer.opacity || '1',
  }],
  ':@': {
    '@_name': 'fill-opacity'
  }
**expectation**
The original value was 0.

Thank you for making the change.

**Comment by KaiVolland** [comment]
Yes this seems to be wrong. Do you want to provide a PR? Otherwise it might need some time until this will be fixed.

**Comment by liqpy** [comment]
I don't know if there are similar issues elsewhere, i just made a simple change to this line of code;
line: 1940;
source code:  
  `'#text': textSymbolizer.opacity || '1',`
change code: 
  `'#text': Number.isFinite(textSymbolizer.opacity) ? textSymbolizer.opacity : '1',`
The output does indeed retain the original value, but more specific inspections are still needed from you, looking forward to you fix it later on.

**Comment by KaiVolland** [comment]
Fixed with #914
