### ISSUE TITLE
Translations of parsers error messages

### ISSUE THREAD

**Issue by slafayIGN** [geostyler/geostyler-sld-parser#923]
Messages from the parsers are in english.

For instance : https://github.com/geostyler/geostyler-sld-parser/blob/master/src/SldStyleParser.ts#L976

```ts
   throw new Error('MarkSymbolizer cannot be parsed. Unsupported WellKnownName.');
```

These messages sometimes have to be displayed for the end user who may be using a UI in another language. It would be great to make the parsers more multilingual.

In addition, the message may contain the "Unsupported WellKnownName". (see #924)

**Comment by ocruze** [comment]
Done in #928
