### ISSUE TITLE
Guessing sld version from file directly and not setting sldVersion as option 

### ISSUE THREAD

**Issue by pprev94** [geostyler/geostyler-sld-parser#925]
Today the parser takes an SLD Version as a parameter.
If the parameter is not set, the default value is `1.0.0`.
It would be a lot more practical to have the parser guess the version from the SLD content itself.

When file content is parsed, the object sldObject contains already version : 
```js
sldObject[0][":@"]["@_version"]
```

if this version is not authorized, an error is thrown. If the version is recognized, it can be set using set sldVersion.

**Comment by jansule** [comment]
solved in https://github.com/geostyler/geostyler-sld-parser/pull/926
