### ISSUE TITLE
`<![CDATA[xxx]]>` not handled correctly

### ISSUE THREAD

**Issue by louwers** [geostyler/geostyler-sld-parser#947]
I reported some issues in [geostyler-cli](https://github.com/geostyler/geostyler-cli/issues/created_by/louwers). But this issue seems unrelated.

When I insert the [following SDL](https://gist.github.com/louwers/7b1465831aa88c72a745222352f87519) which contains

```
								<ogc:Literal><![CDATA[10202]]></ogc:Literal>
								<ogc:Literal><![CDATA[10200]]></ogc:Literal>
								<ogc:Literal><![CDATA[10201]]></ogc:Literal>
```

Then I see e.g.

```
ules": [
    {
      "name": "autosnelweg",
      "filter": [
        "==",
        {
          "name": "in",
          "args": [
            {
              "name": "property",
              "args": [
                "visualisatiecode"
              ]
            },
            null,
            null,
            null
          ]
        },
        true
      ],
      "scaleDenominator": {
        "max": 40000
      },
      "symbolizers": [
        {
          "kind": "Fill",
          "color": "#996089"
        }
      ]
    },
```

When I remove the CDATA then

```
            null,
            null,
            null
```

becomes

```
            10202,
            10200,
            10201
```

I am not an XML expert, but they seem to be part of the standard so I think this is a bug. https://www.w3.org/TR/REC-xml/#sec-cdata-sect

**Comment by KaiVolland** [comment]
Thanks for the report. I'm afraid that we will have to check for every property here and add some kind of wrapper method to check if a value contains CDATA. This might take some time to be resolved.

**Comment by louwers** [comment]
Do you implement your own XML parser? Maybe using a existing XML parser that handles this is an option?

**Comment by KaiVolland** [comment]
We're using [fast-xml-parser](https://www.npmjs.com/package/fast-xml-parser).

**Comment by louwers** [comment]
May be an upstream bug then.
